spring.application.name=mundeuk

spring.config.import=optional:file:.env[.properties]

# \uAC1C\uBC1C DB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}