spring.application.name=mundeuk

spring.config.import=optional:file:.env[.properties]

# 개발 DB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 카카오 검색 API
book.api.key=${REST_API_KEY}
